CREATE TABLE subscription_transaction (
  TRANSACTION_ID int IDENTITY(1,1),
  SUBSCRIPTION_ID INT DEFAULT NULL,
  AMOUNT decimal(16,2) DEFAULT NULL,
  USER_BILLING_ID INT DEFAULT NULL,
  TRANSACTION_STATUS varchar(20) DEFAULT NULL,
  CREATED_ON datetime DEFAULT NULL,
  PRIMARY KEY (TRANSACTION_ID)
);

CREATE TABLE SUBSCRIPTION (
  SUBSCRIPTION_ID int IDENTITY(1,1),
  TOTAL_COST DECIMAL(16,2) DEFAULT NULL,
  CURRENCY_CODE VARCHAR(4) DEFAULT NULL,
  NO_OF_USERS INT DEFAULT NULL,
  NO_OF_COUNTRIES INT DEFAULT NULL,
  TOTAL_DISCOUNT DECIMAL(16,2) DEFAULT NULL,
  EFFECTIVE_FROM_DATE DATETIME DEFAULT NULL,
  EFFECTIVE_TO_DATE DATETIME DEFAULT NULL,
  CREATED_ON DATETIME DEFAULT NULL,
  MODIFIED_ON DATETIME DEFAULT NULL,
  STATUS VARCHAR(1) DEFAULT NULL,
  PRIMARY KEY (SUBSCRIPTION_ID)
) ;

CREATE TABLE SUBSCRIPTION_COUNTRY (
  SUBSCRIPTION_ID INT NOT NULL,
  COUNTRY_CODE VARCHAR(4) NOT NULL,
  CREATED_ON DATETIME DEFAULT NULL,
  MODIFIED_ON DATETIME DEFAULT NULL,
  STATUS VARCHAR(1) DEFAULT NULL,
  PRIMARY KEY (SUBSCRIPTION_ID,COUNTRY_CODE)
) ;

CREATE TABLE SUBSCRIPTION_PRODUCT (
  SUBSCRIPTION_ID INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  CREATED_ON DATETIME DEFAULT NULL,
  MODIFIED_ON DATETIME DEFAULT NULL,
  STATUS VARCHAR(1) DEFAULT NULL,
  PRIMARY KEY (SUBSCRIPTION_ID,PRODUCT_ID)
) ;

CREATE TABLE SUBSCRIPTION_USER (
  SUBSCRIPTION_ID INT NOT NULL,
  USER_ID INT NOT NULL,
  CREATED_ON DATETIME DEFAULT NULL,
  MODIFIED_ON DATETIME DEFAULT NULL,
  STATUS VARCHAR(1) DEFAULT NULL,
  PRIMARY KEY (SUBSCRIPTION_ID,USER_ID)
) ;

CREATE TABLE "USER" (
  ID INT IDENTITY(1,1),
  TITLE VARCHAR(50) DEFAULT NULL,
  FIRST_NAME VARCHAR(50) DEFAULT NULL,
  LAST_NAME VARCHAR(50) DEFAULT NULL,
  EMAIL_ID VARCHAR(50) DEFAULT NULL,
  PHONE VARCHAR(20) DEFAULT NULL,
  COMPANY_NAME VARCHAR(50) DEFAULT NULL,
  IMAGE VARBINARY(MAX),
  PASSWORD VARCHAR(50) DEFAULT NULL,
  RESET_PASSWORD_FLAG VARCHAR(1) DEFAULT NULL,
  USER_TYPE VARCHAR(1) DEFAULT NULL,
  PARENT_USER_ID INT,
  CREATED_ON DATETIME DEFAULT NULL,
  MODIFIED_ON DATETIME DEFAULT NULL,
  PWD_CHANGE_DATETIME DATETIME DEFAULT NULL,
  LAST_LOGGED_IN DATETIME DEFAULT NULL,
  STATUS VARCHAR(1) DEFAULT NULL,
  PRIMARY KEY (ID)
) ;

alter table "user" add sbu varchar(4);

CREATE TABLE user_billing (
  ID INT IDENTITY(1,1),
  USER_ID INT DEFAULT NULL,
  IS_PRIMARY varchar(1) DEFAULT NULL,
  CARD_NO varchar(1000),
  EXP_DATE datetime DEFAULT NULL,
  FIRST_NAME varchar(50) DEFAULT NULL,
  LAST_NAME varchar(50) DEFAULT NULL,
  ADDRESS1 varchar(50) DEFAULT NULL,
  ADDRESS2 varchar(50) DEFAULT NULL,
  CITY varchar(50) DEFAULT NULL,
  STATE varchar(50) DEFAULT NULL,
  COUNTRY_CODE varchar(4) DEFAULT NULL,
  ZIPCODE INT DEFAULT NULL,
  CREATED_ON datetime DEFAULT NULL,
  MODIFIED_ON datetime DEFAULT NULL,
  STATUS varchar(1) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE SUPPORT_CASE (
  TICKET_ID INT IDENTITY(1,1),
  DESCRIPTION VARCHAR(2000),
  CATEGORY INT,
  PRIORITY VARCHAR(1) ,
  CREATED_BY INT,
  CREATED_ON DATETIME ,
  ASSIGNED_TO INT,
  ASSIGNED_ON DATETIME,
  STATUS VARCHAR(1),
  PRIMARY KEY (TICKET_ID)
) ;

CREATE TABLE CASE_LOG (
  ID INT IDENTITY(1,1),
  TICKET_ID INT,
  MESSAGE VARCHAR(2000) DEFAULT NULL,
  MESSAGE_BY INT,
  MESSAGE_ON DATETIME DEFAULT NULL,
  PRIMARY KEY (ID)
) ;

create table ALERTS(
ID INT IDENTITY(1,1),
DESCRIPTION VARCHAR(1000),
EFFECTIVE_FROM_DATE DATETIME ,
EFFECTIVE_TO_DATE DATETIME ,
STATUS VARCHAR(1),
PRIMARY KEY (ID)
);
alter table ALERTS add USER_ID INT;

create table MESSAGES(
ID INT IDENTITY(1,1),
USER_ID INT,
DESCRIPTION VARCHAR(1000),
CREATED_DATE DATETIME ,
STATUS VARCHAR(1),
TICKET_ID INT,
PRIMARY KEY (ID)
);



CREATE TABLE SHIPMENTS(
  ID INT IDENTITY(1,1),
  SHIPMENT_NO VARCHAR(100),
  EXPORT_DATE DATETIME,
  EXPORT_COUNTRY_NAME VARCHAR(100),
  EXPORT_COUNTRY_CODE VARCHAR(10),
  ULT_CONSIGNEE_COUNTRY_NAME VARCHAR(100),
  ULT_CONSIGNEE_COUNTRY_CODE VARCHAR(10), 
  EXPORTER_FIRST_NAME VARCHAR(100),
  EXPORTER_LAST_NAME VARCHAR(100),
  EXPORTER_COMPANY_NAME VARCHAR(100),
  EXPORTER_PHONE_NO VARCHAR(30),
  EXPORTER_EMAIL VARCHAR(80),
  EXPORTER_NAME VARCHAR(100),
  EXPORTER_ADDR_LINE1 VARCHAR(200),
  EXPORTER_ADDR_LINE2 VARCHAR(200),
  EXPORTER_CITY VARCHAR(100),
  EXPORTER_STATE VARCHAR(100),
  EXPORTER_COUNTRY VARCHAR(10),
  EXPORTER_COUNTRY_NAME VARCHAR(100),
  EXPORTER_ZIP VARCHAR(50),
  USPPI_MOT VARCHAR(50),
  USPPI_FIRST_NAME VARCHAR(100),
  USPPI_LAST_NAME VARCHAR(100),
  USPPI_PHONE VARCHAR(30),
  USPPI_PORT_EXPORT VARCHAR(100),
  USPPI_EXPORTER_ID VARCHAR(100),
  USPPI_EXPORTER_IDTYPE VARCHAR(100),
  
  UTL_CONS_NAME VARCHAR(200),
  UTL_CONS_FIRST_NAME VARCHAR(200),
  UTL_CONS_LAST_NAME VARCHAR(200),
  UTL_CONS_ADDR1 VARCHAR(200),
  UTL_CONS_ADDR2 VARCHAR(200),
  UTL_CONS_CITY VARCHAR(200),
  UTL_CONS_STATE VARCHAR(200),
  UTL_CONS_COUNTRY_CODE VARCHAR(200),
  UTL_CONS_COUNTRY_NAME VARCHAR(200),
  UTL_CONS_ZIP VARCHAR(200),
  UTL_CONS_COMPANY_NAME VARCHAR(200),
  UTL_CONS_PHONE VARCHAR(200),
  UTL_CONS_EMAIL VARCHAR(200),
  
  INTER_CONS_NAME VARCHAR(200),
  INTER_CONS_FIRST_NAME VARCHAR(200),
  INTER_CONS_LAST_NAME VARCHAR(200),
  INTER_CONS_ADDR1 VARCHAR(200),
  INTER_CONS_ADDR2 VARCHAR(200),
  INTER_CONS_CITY VARCHAR(200),
  INTER_CONS_STATE VARCHAR(200),
  INTER_CONS_COUNTRY_CODE VARCHAR(200),
  INTER_CONS_COUNTRY_NAME VARCHAR(200),
  INTER_CONS_ZIP VARCHAR(200),
  INTER_CONS_COMPANY_NAME VARCHAR(200),
  INTER_CONS_PHONE VARCHAR(200),
  INTER_CONS_EMAIL VARCHAR(200),
  
  FREIGHT_FW_NAME VARCHAR(200),
  FREIGHT_FW_FIRST_NAME VARCHAR(200),
  FREIGHT_FW_LAST_NAME VARCHAR(200),
  FREIGHT_FW_ADDR1 VARCHAR(200),
  FREIGHT_FW_ADDR2 VARCHAR(200),
  FREIGHT_FW_CITY VARCHAR(200),
  FREIGHT_FW_STATE VARCHAR(200),
  FREIGHT_FW_COUNTRY_CODE VARCHAR(200),
  FREIGHT_FW_COUNTRY_NAME VARCHAR(200),
  FREIGHT_FW_ZIP VARCHAR(200),
  FREIGHT_FW_COMPANY_NAME VARCHAR(200),
  FREIGHT_FW_PHONE VARCHAR(200),
  FREIGHT_FW_EMAIL VARCHAR(200),
    
  PAYMENT_TERMS VARCHAR(200),
  INCO_TERMS VARCHAR(200),
  CURRENCY VARCHAR(50),
  CONVERSION_RATE DECIMAL(16,2),
  PO_NUMBER VARCHAR(200),
  MODE_OF_TRANSPORT VARCHAR(100),
  FREIGHT_CHARGES_PAID_BY VARCHAR(200),
  FOREIGN_VAT_PAID_BY VARCHAR(200),
  CUSTOM_DUTY_PAID_BY VARCHAR(200),
  CHARGE_DESC VARCHAR(200),
  CHARGE_AMT DECIMAL(16,4),
  DROP_SHIPMENT VARCHAR(1),
  SHIP_TO VARCHAR(50),
  BILL_TO VARCHAR(50),
  CONTAIN_PERSONAL_EFFECT VARCHAR(1),
  INSURANCE_REQUIRED VARCHAR(1),
  CHARGE_TO_CUSTOMER VARCHAR(1),
  PRINT_ON_DOC VARCHAR(1),
  
  SPECIAL_INSTRUCTION VARCHAR(255),
  SHIPMENT_INSTRUCTION VARCHAR(255),
  
  SCREENING_STATUS varchar(20),
  SCREENED_ON DATETIME,
  LS_STATUS varchar(10),
  
  STATUS varchar(20),
  CREATED_ON DATETIME,
  CREATED_BY VARCHAR(20),
  MODIFIED_ON DATETIME,
  MODIFIED_BY VARCHAR(20),
  PRIMARY KEY (ID)
);

alter table shipments add constraint shipNo_unique UNIQUE(shipment_no);
 
CREATE TABLE SHIPMENT_ITEM(
  ID INT IDENTITY(1,1),
  ITEM_NO INT NOT NULL,
  SHIPMENT_ID INT,
  PART_NO VARCHAR(255),
  USML_CATEGORY VARCHAR(255),
  HTS_SCHEDULE_B VARCHAR(50),
  HTS_SCHEDULE_UOM VARCHAR(50),
  ECCN VARCHAR(100),
  IMPORT_HTS VARCHAR(50),
  IMPORT_HTS_UOM VARCHAR(50),
  COO VARCHAR(50),
  MANUFACTURER VARCHAR(100),
  SERIAL_NUMBERS TEXT,
  PRODUCT_DESC TEXT,
  INVOICE_QTY DECIMAL(16,4),
  INVOICE_VALUE DECIMAL(16,4),
  DISCOUNT DECIMAL(16,2),
  CURRENCY VARCHAR(100),
  CONVERSION_RATE DECIMAL(16,4),
  WHOLESALE_RATE DECIMAL(16,4),
  UNIT_PRICE DECIMAL(16,4),
  WHOLESALE_VALUE DECIMAL(16,4),
  GROSS_WEIGHT DECIMAL(16,4),
  NET_WEIGHT DECIMAL(16,4), 
  
  LICENSE_REQUIRED VARCHAR(10),
  SCREEN_TYPE VARCHAR(20),
  SCREENED_ON DATETIME,
  
  FOREIGN KEY (SHIPMENT_ID) REFERENCES SHIPMENTS(id),
  PRIMARY KEY (ID)
);

CREATE TABLE SHIPMENT_CARTON(
  ID INT IDENTITY(1,1),
  SHIPMENT_ID INT,
  PACKAGE_NO INT,
  CARTON_NO INT,
  HAZMAT VARCHAR(100),
  DIMENSION_UOM VARCHAR(100),
  WEIGHT_UOM VARCHAR(100),
  LENGTH DECIMAL(16,4),
  WIDTH DECIMAL(16,4),
  HEIGHT DECIMAL(16,4),
  GROSS_WEIGHT DECIMAL(16,4),
  NET_WEIGHT DECIMAL(16,4),
  FOREIGN KEY (SHIPMENT_ID) REFERENCES SHIPMENTS(id),
  PRIMARY KEY (ID)
);

CREATE TABLE SHIPMENT_DOCS(
  ID INT IDENTITY(1,1),
  SHIPMENT_ID int not null,
  FILE_TYPE VARCHAR(100),
  FILE_NAME VARCHAR(255),
  FILE_PATH VARCHAR(255),
  CREATED_ON DATETIME,
  CREATED_BY VARCHAR(20),
  MODIFIED_ON DATETIME,
  MODIFIED_BY VARCHAR(20),
  FOREIGN KEY (SHIPMENT_ID) REFERENCES SHIPMENTS(id),
  PRIMARY KEY(ID)
);

CREATE TABLE CLIENT(
	ACCOUNT_ID varchar(20) NOT NULL,
	CLIENT_NAME varchar(100) NULL,
	STATUS varchar(20) NULL,
	EMAIL_ID varchar(100) NULL,
	PASSWORD varchar(100) NULL,
	CREATED_DATE datetime NULL,
	MODIFIED_DATE datetime NULL,
	CREATED_BY varchar(100) NULL,
	MODIFIED_BY varchar(20) NULL,
	SERVER_NAME varchar(250) NOT NULL,
	HOST_NAME varchar(250) NOT NULL,
	CLIENT_IP_ADD varchar(100) NULL,
	PRIMARY KEY  
	(
		ACCOUNT_ID,
		SERVER_NAME,
		HOST_NAME
	)
);

CREATE TABLE partner_url_details(
       ID int NOT NULL,
       PARTNER_NAME varchar(45),
       API_NAME varchar(45),
       URL varchar(200),
       PRIMARY KEY 
       (
              ID 
       )
);

ALTER TABLE partner_url_details ADD ACC_NO VARCHAR(50) ;
ALTER TABLE partner_url_details ADD USERNAME VARCHAR(50) ;
ALTER TABLE partner_url_details ADD PASSWORD VARCHAR(50) ;

CREATE TABLE security_params(
       ID int NOT NULL,
       SBU_CODE varchar(45) ,
       ACCOUNT varchar(45) ,
       PARTNER_NAME varchar(45) NOT NULL,
       USERNAME varchar(30) ,
       PASSWORD varchar(45) ,
       ACCOUNT_NUMBER varchar(45) ,
       METER_NUMBER varchar(45) ,
       LICENSE_NUMBER varchar(45) ,
       PRIMARY KEY 
       (
              ID 
       )
);
ALTER TABLE security_params ADD THIRD_PARTY_ACC_NO VARCHAR(45) ;
ALTER TABLE security_params ADD BILL_TO VARCHAR(20) ;
ALTER TABLE security_params ADD SPR_NAME VARCHAR(200) ;
ALTER TABLE security_params ADD SPR_CONTACT_FIRST_NAME VARCHAR(200) ;
ALTER TABLE security_params ADD SPR_CONTACT_MIDDLE_NAME VARCHAR(200) ;
ALTER TABLE security_params ADD SPR_CONTACT_LAST_NAME VARCHAR(200) ;
ALTER TABLE security_params ADD SPR_ADDR_LINE1 VARCHAR(255) ;
ALTER TABLE security_params ADD SPR_ADDR_LINE2 VARCHAR(255) ;
ALTER TABLE security_params ADD SPR_CITY_NAME VARCHAR(100) ;
ALTER TABLE security_params ADD SPR_CITY_CODE VARCHAR(10) ;
ALTER TABLE security_params ADD SPR_STATE_NAME VARCHAR(100) ;
ALTER TABLE security_params ADD SPR_STATE_CODE VARCHAR(10) ;
ALTER TABLE security_params ADD SPR_COUNTRY_NAME VARCHAR(100) ;
ALTER TABLE security_params ADD SPR_COUNTRY_CODE VARCHAR(10) ;
ALTER TABLE security_params ADD SPR_ZIP VARCHAR(50) ;
ALTER TABLE security_params ADD SPR_PHONENO VARCHAR(50) ;
ALTER TABLE security_params ADD SPR_EMAIL VARCHAR(100) ;
ALTER TABLE security_params ADD BILL_TO_NAME VARCHAR(200) ;
ALTER TABLE security_params ADD BILL_TO_FIRST_NAME VARCHAR(200) ;
ALTER TABLE security_params ADD BILL_TO_MIDDLE_NAME VARCHAR(200) ;
ALTER TABLE security_params ADD BILL_TO_LAST_NAME VARCHAR(200) ;
ALTER TABLE security_params ADD BILL_TO_ADDR_LINE1 VARCHAR(255) ;
ALTER TABLE security_params ADD BILL_TO_ADDR_LINE2 VARCHAR(255) ;
ALTER TABLE security_params ADD BILL_TO_CITY_NAME VARCHAR(100) ;
ALTER TABLE security_params ADD BILL_TO_CITY_CODE VARCHAR(10) ;
ALTER TABLE security_params ADD BILL_TO_STATE_NAME VARCHAR(100) ;
ALTER TABLE security_params ADD BILL_TO_STATE_CODE VARCHAR(10) ;
ALTER TABLE security_params ADD BILL_TO_COUNTRY_NAME VARCHAR(100) ;
ALTER TABLE security_params ADD BILL_TO_COUNTRY_CODE VARCHAR(10) ;
ALTER TABLE security_params ADD BILL_TO_ZIP VARCHAR(50) ;
ALTER TABLE security_params ADD BILL_TO_PHONENO VARCHAR(50) ;
ALTER TABLE security_params ADD BILL_TO_EMAIL VARCHAR(100) ;

create table SBU_CONFIG(
	   ID int IDENTITY(1,1),
       SBU varchar(45),
       NAME varchar(255),
       CONFIG_VALUE varchar(255),
       DESCRIPTION VARCHAR(2000),
       STATUS VARCHAR(20),       
       CREATED_ON datetime,
       CREATED_BY VARCHAR(50),
       MODIFIED_ON datetime,
       MODIFIED_BY VARCHAR(50),
       PRIMARY KEY 
       (
              ID 
       )
);

ALTER TABLE SHIPMENTS ADD EXPORTER_CODE VARCHAR(100);
ALTER TABLE SHIPMENTS ADD ULT_CONSIGNEE_CODE VARCHAR(100);
ALTER TABLE SHIPMENTS ADD INTER_CONSIGNEE_CODE VARCHAR(100);
ALTER TABLE SHIPMENTS ADD FF_CODE VARCHAR(100);

ALTER TABLE SHIPMENTS ADD SHIP_TO_CODE VARCHAR(100);
ALTER TABLE SHIPMENTS ADD SHIP_TO_NAME VARCHAR(200);
ALTER TABLE SHIPMENTS ADD SHIP_TO_CITY VARCHAR(50);
ALTER TABLE SHIPMENTS ADD SHIP_TO_STATE VARCHAR(50);
ALTER TABLE SHIPMENTS ADD SHIP_TO_COUNTRY VARCHAR(50);
ALTER TABLE SHIPMENTS ADD SHIP_TO_ZIP VARCHAR(30);
ALTER TABLE SHIPMENTS ADD SHIP_TO_ADDR1 VARCHAR(255);
ALTER TABLE SHIPMENTS ADD SHIP_TO_ADDR2 VARCHAR(255);

ALTER TABLE SHIPMENTS ADD BILL_TO_CODE VARCHAR(100);
ALTER TABLE SHIPMENTS ADD BILL_TO_NAME VARCHAR(200);
ALTER TABLE SHIPMENTS ADD BILL_TO_CITY VARCHAR(50);
ALTER TABLE SHIPMENTS ADD BILL_TO_STATE VARCHAR(50);
ALTER TABLE SHIPMENTS ADD BILL_TO_COUNTRY VARCHAR(50);
ALTER TABLE SHIPMENTS ADD BILL_TO_ZIP VARCHAR(30);
ALTER TABLE SHIPMENTS ADD BILL_TO_ADDR1 VARCHAR(255);
ALTER TABLE SHIPMENTS ADD BILL_TO_ADDR2 VARCHAR(255);
ALTER TABLE SHIPMENTS ADD AES_OPTION VARCHAR(20);

INSERT INTO STATE_PROVINCE (STATE_CODE, STATE_NAME, COUNTRY_CODE, STATUS, CREATED_BY, created_on, modified_by, modified_on) 
VALUES 
('CA','California','US','A',NULL,NULL,NULL,NULL),('DL','New Delhi','IN','A',NULL,NULL,NULL,NULL),('DMS','Damascus','SY','A',NULL,NULL,NULL,NULL),('IS','Islamabad','PK','A',NULL,NULL,NULL,NULL),('KDH','Kandadhar','AF','A',NULL,NULL,NULL,NULL),('MH','Maharashtra','IN','A',NULL,NULL,NULL,NULL),('MO','Mosul','IQ','A',NULL,NULL,NULL,NULL),('NY','New York','US','A',NULL,NULL,NULL,NULL),('PB','Punjab','IN','A',NULL,NULL,NULL,NULL),('SD','Sindh','PK','A',NULL,NULL,NULL,NULL),('JS','London','GB','A',NULL,NULL,NULL,NULL);

ALTER TABLE SHIPMENTS ADD FIILER_TYPE_ID VARCHAR(5);
ALTER TABLE SHIPMENTS ADD ULT_CONS_TYPE VARCHAR(50);
ALTER TABLE SHIPMENTS ADD TRANSMIT_TO_AES VARCHAR(5);
ALTER TABLE SHIPMENTS ADD FF_FILTER_ID_TYPE VARCHAR(5);
ALTER TABLE SHIPMENTS ADD FF_FILTER_ID_NO VARCHAR(50);

ALTER TABLE SHIPMENTS ADD RELATED_PARTY_TRANSACTION VARCHAR(50);
ALTER TABLE SHIPMENTS ADD SHIPMENT_REF_NO VARCHAR(50);
ALTER TABLE SHIPMENTS ADD HAZDAROUS VARCHAR(5);
ALTER TABLE SHIPMENTS ADD MOT_CODE VARCHAR(10);
ALTER TABLE SHIPMENTS ADD PORT_UNLANDING VARCHAR(50);
ALTER TABLE SHIPMENTS ADD PORT_UNLANDING_CODE VARCHAR(10);
ALTER TABLE SHIPMENTS ADD TRANSPORT_REF_NO VARCHAR(100);
ALTER TABLE SHIPMENTS ADD ENTRY_NUMBER VARCHAR(100);
ALTER TABLE SHIPMENTS ADD CONVEYANCE_NAME VARCHAR(100);

ALTER TABLE SHIPMENTS ADD BOOKING_NO varchar(255);
ALTER TABLE SHIPMENTS ADD TRACKING_NO varchar(255);
ALTER TABLE SHIPMENTS ADD COO_NAME varchar(255);
ALTER TABLE SHIPMENTS ADD COO_CODE varchar(10);
ALTER TABLE SHIPMENTS ADD PORT_OF_EXPORT_NAME varchar(255);
ALTER TABLE SHIPMENTS ADD PORT_OF_EXPORT_CODE varchar(20);
ALTER TABLE SHIPMENTS ADD PORT_OF_UNLOAD_NAME varchar(255);
ALTER TABLE SHIPMENTS ADD PORT_OF_UNLOAD_CODE varchar(20);
ALTER TABLE SHIPMENTS ADD PORT_OF_ARRIVAL_NAME varchar(255);
ALTER TABLE SHIPMENTS ADD PORT_OF_ARRIVAL_CODE varchar(20);
ALTER TABLE SHIPMENTS ADD SHIPMENT_CAERRIR_NAME varchar(255);
ALTER TABLE SHIPMENTS ADD SHIPMENT_CAERRIR_CODE varchar(20);
ALTER TABLE SHIPMENTS ADD FINAL_DEST_AIRPORT varchar(255);
ALTER TABLE SHIPMENTS ADD VESSEL_FLIGHT_NO varchar(255);
ALTER TABLE SHIPMENTS ADD TRANSPORT_DOC_NO varchar(255);

ALTER TABLE SHIPMENTS ADD EEI_NO varchar(255);
ALTER TABLE SHIPMENTS ADD AES_STATUS varchar(255);
ALTER TABLE SHIPMENTS ADD ITN varchar(255);
ALTER TABLE SHIPMENTS ADD ROUTED_EXP_TXN varchar(255);
ALTER TABLE SHIPMENTS ADD RELATED_PRTY_TXN varchar(255);
ALTER TABLE SHIPMENTS ADD STATE_OF_ORIGIN varchar(255);
ALTER TABLE SHIPMENTS ADD FTZ_NO varchar(255);

ALTER TABLE SHIPMENT_ITEM ADD CONTROLLING_AGENCY varchar(255);
ALTER TABLE SHIPMENT_ITEM ADD BIS_LICENSE_EXCEPTION varchar(255);
ALTER TABLE SHIPMENT_ITEM ADD ITAR_EXEMPTION varchar(255);
ALTER TABLE SHIPMENT_ITEM ADD LICENSE_NO varchar(255);
ALTER TABLE SHIPMENT_ITEM ADD LICENSE_CODE varchar(255);
ALTER TABLE SHIPMENT_ITEM ADD LICENSE_TYPE varchar(50);
ALTER TABLE SHIPMENT_ITEM ADD LICENSE_EXP_DATE DATETIME;
ALTER TABLE SHIPMENT_ITEM ADD SME_INDICATOR varchar(10);
ALTER TABLE SHIPMENT_ITEM ADD DDTC_QUANTITY DECIMAL(16,4);
ALTER TABLE SHIPMENT_ITEM ADD DDTC_UOM varchar(255);
ALTER TABLE SHIPMENT_ITEM ADD DDTC_ELIGIBILITY_PARTY varchar(255);
ALTER TABLE SHIPMENT_ITEM ADD DDTC_REGISTRATION_NO varchar(255);
ALTER TABLE SHIPMENT_ITEM ADD APPROVED_COMMUNITY_NO varchar(255);
ALTER TABLE SHIPMENT_ITEM ADD FTR_EFFECTIVE_DATE DATETIME;
ALTER TABLE SHIPMENT_ITEM ADD COO_CODE varchar(5);

ALTER TABLE SHIPMENT_ITEM ADD REPORT_REQ varchar(5);

CREATE TABLE THEMES(
	USER_ID INT,
	GTN_CLASS VARCHAR(100),
	SBU VARCHAR(20),
	DEFAULT_CLASS VARCHAR(100),
	PRIMARY KEY(
		USER_ID,
		SBU
	)
);

CREATE TABLE PRODUCTS(
	
	PART_NO VARCHAR(100) NOT NULL,
	PART_DESC VARCHAR(2000),
	PART_TYPE VARCHAR(10),
	MATERIAL_TYPE VARCHAR(200),
	UNIT_PRICE DECIMAL(16, 4),
	CURRENCY VARCHAR(3),
	SKU_NO VARCHAR(100),
	MODEL_NO VARCHAR(200),
	NET_WEIGHT DECIMAL(16, 4),
	UOM_PRICE VARCHAR(100),
	EXPORT_CLASS VARCHAR(200),
	IMPORT_CLASS VARCHAR(200),
	HAZMAT VARCHAR(10),
	HAZMAT_CODE VARCHAR(100),
	HAZMAT_DESC VARCHAR(2000),
	FLASH_POINT_TEMP VARCHAR(40),
	HAZMAT_CONTACT_NAME VARCHAR(200),
	HAZMAT_CONTACT_PHONE VARCHAR(20),
	SBU_CODE varchar(100),
	
	CREATED_BY VARCHAR(200),
	CREATED_ON DATETIME,
	UPDATED_BY VARCHAR(200),
	UPDATED_ON DATETIME,
	
	PRIMARY KEY(
		PART_NO
	)
);


CREATE TABLE PRODUCTS_MANUFACTURER(
	PRODUCT_ID varchar(100) not null,
	ITEM_NO int not null,
	DEFAULT_MANUF varchar(10),
	MANUF_ID varchar(100),
	NAME varchar(255),
	MANUF_MODEL_NO varchar(100),
	MANUF_PART_NO varchar(100),
	COO_CODE varchar(10),
	COO_NAME varchar(100),
	CONTACT_NAME varchar(200),
	EMAIL varchar(100),
	TELEPHONE varchar(20),
	ASSIST_VALUE decimal(16, 4),
	ASSIST_BALANCE decimal(16, 4),
	
	CREATED_BY VARCHAR(200),
	CREATED_ON DATETIME,
	UPDATED_BY VARCHAR(200),
	UPDATED_ON DATETIME,
	
	primary key(
		PRODUCT_ID,
		item_no
	)
);

alter table EXPORTER add EMAIL varchar(50);
alter table SHIPMENTS add  EXPORTER_STATE_NAME varchar(100);
alter table SHIPMENTS add  UTL_CONS_STATE_NAME varchar(100);
alter table SHIPMENTS add  INTER_CONS_STATE_NAME varchar(100);
alter table SHIPMENTS add  FREIGHT_FW_STATE_NAME varchar(100);
alter table SHIPMENTS add  SBU_CODE varchar(10);
alter table SHIPMENTS add  MODE_OF_TRANSPORT_CODE varchar(10);
ALTER TABLE SHIPMENTS modify ACC_NO VARCHAR(50) ;

alter table shipments drop column CREATED_BY;
alter table shipments add CREATED_BY varchar(100);

alter table SHIPMENTS add  BILL_TO_COUNTRY_NAME varchar(50);
alter table SHIPMENTS add  BILL_TO_STATE_NAME varchar(50);
alter table SHIPMENTS add  SHIP_TO_STATE_NAME varchar(50);
alter table SHIPMENTS add  SHIP_TO_COUNTRY_NAME varchar(50);
alter table SHIPMENTS add  CORRECTION_CODE varchar(10);
alter table SHIPMENTS add  XTN_NUMBER varchar(20);
alter table SHIPMENTS add  EASE_STATUS varchar(20);

alter table shipments drop column MODIFIED_BY;
alter table shipments add MODIFIED_BY varchar(100);
alter table shipments add EASE_SUBMIT_DATE DATETIME;


CREATE TABLE AES_STATUS_HISTORY (
	ID INT IDENTITY(1,1),
	SHIPMENT_NO VARCHAR(50),
	SUBMITTED_ON DATETIME,
	RESPONDED_ON DATETIME,
	OLD_AES_STATUS VARCHAR(5),
	NEW_AES_STATUS VARCHAR(5),
	OLD_ITN_NO VARCHAR(20),
	NEW_ITN_NO VARCHAR(20),
	OLD_XTN_NO VARCHAR(20),
	NEW_XTN_NO VARCHAR(20),
	OLD_CORRECTION_CODE VARCHAR(5),
	NEW_CORRECTION_CODE VARCHAR(5),
	PRIMARY KEY(
		ID
	)
);

CREATE TABLE JOB_SCHEDULAR(
	JOB_CODE VARCHAR(50),
	JOB_NAME VARCHAR(100),
	CRON VARCHAR(40),
	CREATED_BY VARCHAR(200),
	CREATED_ON DATETIME,
	MODIFIED_BY VARCHAR(200),
	MODIFIED_ON DATETIME,
	PRIMARY KEY(
		JOB_CODE
	)
);
alter table JOB_SCHEDULAR add JOB_DESCRIPTION varchar(2000);

INSERT INTO JOB_SCHEDULAR(JOB_CODE, JOB_NAME, CRON, CREATED_BY, CREATED_ON) VALUES ('AES_FILING', 'AES FILING', '0 0 20 * * *', 'naveen.kumar@aarininc.com', CURRENT_TIMESTAMP);

CREATE TABLE PRODUCT (
  PRODUCT_ID INT NOT NULL IDENTITY,
  DISPLAY_NAME VARCHAR(50) DEFAULT NULL,
  DESCRIPTION VARCHAR(500) DEFAULT NULL,
  LEVEL INT DEFAULT NULL,
  PARENT_PRODUCT_ID INT DEFAULT NULL,
  COST DECIMAL(16,2) DEFAULT NULL,
  CURRENCY_CODE VARCHAR(4) DEFAULT NULL,
  DISCOUNT_PERCENTAGE DECIMAL(3,2) DEFAULT NULL,
  STATUS VARCHAR(1) DEFAULT NULL,
  PRIMARY KEY (PRODUCT_ID)
) ;


alter table product add ITEM_POSITION int;

update PRODUCT set ITEM_POSITION = 0 where PRODUCT_ID = 1;
GO
update PRODUCT set ITEM_POSITION = 0 where PRODUCT_ID = 2;
GO
update PRODUCT set ITEM_POSITION = 1 where PRODUCT_ID = 3;
GO
update PRODUCT set ITEM_POSITION = 1 where PRODUCT_ID = 4;
GO
update PRODUCT set ITEM_POSITION = 0 where PRODUCT_ID = 5;
GO
update PRODUCT set ITEM_POSITION = 1 where PRODUCT_ID = 6;
GO
update PRODUCT set ITEM_POSITION = 2 where PRODUCT_ID = 7;
GO
update PRODUCT set ITEM_POSITION = 3 where PRODUCT_ID = 8;
GO
update PRODUCT set ITEM_POSITION = 4 where PRODUCT_ID = 9;
GO
update PRODUCT set ITEM_POSITION = 2 where PRODUCT_ID = 10;
GO
update PRODUCT set ITEM_POSITION = 0 where PRODUCT_ID = 11;
GO
update PRODUCT set ITEM_POSITION = 1 where PRODUCT_ID = 12;
GO
update PRODUCT set ITEM_POSITION = 2 where PRODUCT_ID = 13;
GO
update PRODUCT set ITEM_POSITION = 3 where PRODUCT_ID = 14;
GO
update PRODUCT set ITEM_POSITION = 0 where PRODUCT_ID = 15;
GO
update PRODUCT set ITEM_POSITION = 1 where PRODUCT_ID = 16;
GO
update PRODUCT set ITEM_POSITION = 4 where PRODUCT_ID = 17;
GO
update PRODUCT set ITEM_POSITION = 0 where PRODUCT_ID = 18;
GO
update PRODUCT set ITEM_POSITION = 1 where PRODUCT_ID = 19;
GO


alter table product add ITEM_URL varchar(150);


insert into product (DISPLAY_NAME, DESCRIPTION, LEVEL, PARENT_PRODUCT_ID, COST, CURRENCY_CODE, DISCOUNT_PERCENTAGE, STATUS, item_position) 
values 
('Business Intelligence', 'Business Intelligence', 1, 1, 10.00, 'USD', 0.00, 'A', 2);


update PRODUCT set ITEM_URL = 'createEntityScreening' where PRODUCT_ID = 2;
GO
update PRODUCT set ITEM_URL = 'createLicenseScreening' where PRODUCT_ID = 3;
GO
update PRODUCT set ITEM_URL = 'createBusinessIntelligence' where PRODUCT_ID = 20;
GO
update PRODUCT set ITEM_URL = 'createShipmentWizard' where PRODUCT_ID = 5;
GO
update PRODUCT set ITEM_URL = 'publication' where PRODUCT_ID = 15;
GO
update PRODUCT set ITEM_URL = 'publication' where PRODUCT_ID = 16;
GO

alter table product add FA_ICON varchar(50);

update PRODUCT set FA_ICON = 'fa-user' where PRODUCT_ID = 1;
GO
update PRODUCT set FA_ICON = 'fa-globe' where PRODUCT_ID = 4;
GO
update PRODUCT set FA_ICON = 'fa-navicon' where PRODUCT_ID = 10;
GO
update PRODUCT set FA_ICON = 'fa-file-powerpoint-o' where PRODUCT_ID = 14;
GO
update PRODUCT set FA_ICON = 'fa-dashboard' where PRODUCT_ID = 17;
GO

insert into subscription_transaction (SUBSCRIPTION_ID, AMOUNT, USER_BILLING_ID, TRANSACTION_STATUS) VALUES (2, 50.00, 111, 'A');
GO


CREATE TABLE MENU (
	  MENU_ID INT NOT NULL IDENTITY,
	  DISPLAY_NAME VARCHAR(50) DEFAULT NULL,
	  DESCRIPTION VARCHAR(500) DEFAULT NULL,
	  LEVEL INT DEFAULT NULL,
	  PARENT_MENU_ID INT DEFAULT NULL,
	  STATUS VARCHAR(1) DEFAULT NULL,
	  ITEM_POSITION INT,
	  ITEM_URL varchar(150),
	  FA_ICON varchar(50),
	  LINK_TYPE varchar(1),
	  PRODUCT_ID INT,
	  PRIMARY KEY (MENU_ID)
);
GO

SET IDENTITY_INSERT MENU ON 

INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (1, N'Global Trade Control', N'Global Trade Control', 0, 0, N'A', 0, NULL, N'fa-user', 'P')
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (2, N'Watch List Screening', N'Watch List Screening', 1, 1,  N'A', 0, N'createEntityScreening', NULL, 'P')
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (3, N'License Screening', N'License Screening', 1, 1,  N'A', 1, N'createLicenseScreening', NULL, 'P')
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (4, N'Export Operations', N'Export Operations', 0, 0, N'A', 1, NULL, N'fa-globe', 'P')
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (5, N'Export Shipment', N'Export Shipment', 1, 4,  N'A', 0, N'createShipmentWizard', NULL, 'P')
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (6, N'Integrated WLS', N'Integrated WLS', 1, 4,  N'A', 1, NULL, NULL, 'P')
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (7, N'Integrated LS', N'Integrated LS', 1, 4,  N'A', 2, NULL, NULL, 'P')
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (8, N'Customs Filing', N'Customs Filing', 1, 4,  N'A', 3, NULL, NULL, 'P')
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (9, N'Logistics Integration', N'Logistics Integration', 1, 4,  N'A', 4, NULL, NULL, 'P')
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (10, N'Import Operations', N'Import Operations', 0, 0, N'A', 2, NULL, N'fa-navicon', 'P')
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (11, N'Import Shipment', N'Import Shipment', 1, 10,  N'A', 0, NULL, NULL, 'P')
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (12, N'Customs Filing', N'Customs Filing', 1, 10,  N'A', 1, NULL, NULL, 'P')
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (13, N'Landed Cost', N'Landed Cost', 1, 10,  N'A', 2, NULL, NULL, 'P')
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (14, N'Publications', N'Publications', 0, 0, N'A', 3, NULL, N'fa-file-powerpoint-o', 'P')
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (15, N'Unlimited Access', N'Unlimited Access', 1, 14,  N'A', 0, N'publication', NULL, 'P')
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (16, N'Annotate Online', N'Annotate Online', 1, 14,  N'A', 1, N'publication', NULL, 'P')
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (17, N'Consulting Services', N'Consulting Services', 0, 0, N'A', 4, NULL, N'fa-dashboard', 'P')
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (18, N'Basic', N'Basic', 1, 17,  N'A', 0, NULL, NULL, 'P')
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (19, N'Annotate Online', N'Advanced', 1, 17,  N'A', 1, NULL, NULL, 'P')
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (20, N'Business Intelligence', N'Business Intelligence', 1, 1, N'A', 2, N'createBusinessIntelligence', NULL, 'P')
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (21, 'Admin', 'Admin', 0, 0, 'A', 5, NULL, 'fa-inbox', 'A');
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (22, 'Schedule Job', 'Schedule Job', 1, 21, N'A', 0, N'createSearchScheduledJob', NULL, 'A');
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (23, N'Global Variable', N'Global Variable', 1, 21, N'A', 1, N'sbuParams', NULL, 'A');
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (24, N'Tables', N'Tables', 0, 0, N'A', 6, NULL, 'fa-table', 'A');
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (25, N'Exporter', N'Exporter', 1, 24, N'A', 0, N'createSearchExporter', NULL, 'A');
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (26, N'Consigneee', N'Consigneee', 1, 24, N'A', 1, N'createSearchConsignee', NULL, 'A');
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (27, N'Product', N'Product', 1, 24, N'A', 2, N'createSearchProduct', NULL, 'A');
INSERT INTO MENU ([MENU_ID], [DISPLAY_NAME], [DESCRIPTION], [LEVEL], [PARENT_MENU_ID],  [STATUS], [ITEM_POSITION], [ITEM_URL], [FA_ICON], [LINK_TYPE]) 
VALUES (28, N'One Time Publications', N'One Time Publications', 1, 14,  N'A', 1, N'publication', NULL, 'P');

SET IDENTITY_INSERT MENU OFF
GO
update menu set product_id = menu_id;
GO
SET IDENTITY_INSERT PRODUCT ON
insert into product(PRODUCT_ID,	DISPLAY_NAME,	DESCRIPTION,	LEVEL,	PARENT_PRODUCT_ID,	COST,	CURRENCY_CODE,	DISCOUNT_PERCENTAGE,	STATUS,	FA_ICON,	ITEM_URL,ITEM_POSITION)
 VALUES('21',	'One Time Publications',	'One Time Publications',	1,	14,	20.00,	'USD',	0.00,	'A',	NULL	,'publication',	2);
 SET IDENTITY_INSERT PRODUCT OFF
 
 
 update menu set product_id = '21' where menu_id='28';
 GO
 
 CREATE TABLE DPL_SCREENINGS(
 	ENTITY_ID VARCHAR(100),
 	ENTITY_TYPE VARCHAR(100),
 	ORG_TYPE VARCHAR(100),
 	CITY VARCHAR(100),
 	NAME VARCHAR(255),
 	STATE VARCHAR(20),
 	STATE_NAME VARCHAR(200),
 	ADDR1 VARCHAR(255),
 	ADDR2 VARCHAR(255),
 	ADDR3 VARCHAR(255),
 	COUNTRY VARCHAR(20),
 	COUNTRY_NAME VARCHAR(100),
 	ZIP VARCHAR(100),
 	
 	HITS INT,
 	MASTER_LINK VARCHAR(1),
 	ENTITY_CODE VARCHAR(100),
 	SCREENED_BY VARCHAR(200),
 	SCREENED_ON DATETIME,
 	
    UNIQUE (ENTITY_ID)
 );
 
 alter table shipments add SHIPMENT_VALUE DECIMAL(16, 4);
 
 
CREATE TABLE [publication_user](
	[publication_id] [int] NOT NULL,
	[USER_ID] [int] NOT NULL,
	[CREATED_ON] [datetime] NULL,
	[MODIFIED_ON] [datetime] NULL,
	[STATUS] [varchar](1) NULL,
PRIMARY KEY 
(
	[publication_id],
	[USER_ID]
)
GO

CREATE TABLE [publication](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TITLE] [varchar](50) NULL,
	[AUTHOR] [varchar](50) NULL,
	[PUBLISH_DATE] [datetime] NULL,
	[PUBLICATION_TYPE] [varchar](50) NULL,
	[DESCRIPTION] [varchar](50) NULL,
	[PUB_URL] [varchar](500) NULL,
	[PRICE] [decimal](16, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)
GO

alter table [publication] add currency_code varchar(50);
GO
update [publication] set currency_code = 'USD'
GO

alter table PUBLICATION add TYPE varchar(100);
GO

ALTER TABLE PUBLICATION alter column TITLE VARCHAR(200) ;
ALTER TABLE PUBLICATION alter column AUTHOR VARCHAR(200) ;
ALTER TABLE PUBLICATION alter column DESCRIPTION VARCHAR(1000) ;
GO

ALTER TABLE SUBSCRIPTION ADD NO_OF_CHILD_USERS_CART INT;
GO

