SET IDENTITY_INSERT product ON 
GO

insert into product (PRODUCT_ID,DISPLAY_NAME,DESCRIPTION,LEVEL,PARENT_PRODUCT_ID,COST,CURRENCY_CODE,DISCOUNT_PERCENTAGE,STATUS)
values (1,'Global Trade Control','Global Trade Control',0,0,0,'USD',0,'A');
insert into product (PRODUCT_ID,DISPLAY_NAME,DESCRIPTION,LEVEL,PARENT_PRODUCT_ID,COST,CURRENCY_CODE,DISCOUNT_PERCENTAGE,STATUS)
values (2,'Watch List Screening','Watch List Screening',1,1,20,'USD',0,'A');
insert into product (PRODUCT_ID,DISPLAY_NAME,DESCRIPTION,LEVEL,PARENT_PRODUCT_ID,COST,CURRENCY_CODE,DISCOUNT_PERCENTAGE,STATUS)
values (3,'License Screening','License Screening',1,1,20,'USD',0,'A');
insert into product (PRODUCT_ID,DISPLAY_NAME,DESCRIPTION,LEVEL,PARENT_PRODUCT_ID,COST,CURRENCY_CODE,DISCOUNT_PERCENTAGE,STATUS)
values (4,'Export Operations','Export Operations',0,0,0,'USD',0,'A');
insert into product (PRODUCT_ID,DISPLAY_NAME,DESCRIPTION,LEVEL,PARENT_PRODUCT_ID,COST,CURRENCY_CODE,DISCOUNT_PERCENTAGE,STATUS)
values (5,'Export Shipment','Export Shipment',1,4,20,'USD',0,'A');
insert into product (PRODUCT_ID,DISPLAY_NAME,DESCRIPTION,LEVEL,PARENT_PRODUCT_ID,COST,CURRENCY_CODE,DISCOUNT_PERCENTAGE,STATUS)
values (6,'Integrated WLS','Integrated WLS',1,4,20,'USD',0,'A');
insert into product (PRODUCT_ID,DISPLAY_NAME,DESCRIPTION,LEVEL,PARENT_PRODUCT_ID,COST,CURRENCY_CODE,DISCOUNT_PERCENTAGE,STATUS)
values (7,'Integrated LS','Integrated LS',1,4,20,'USD',0,'A');
insert into product (PRODUCT_ID,DISPLAY_NAME,DESCRIPTION,LEVEL,PARENT_PRODUCT_ID,COST,CURRENCY_CODE,DISCOUNT_PERCENTAGE,STATUS)
values (8,'Customs Filing','Customs Filing',1,4,20,'USD',0,'A');
insert into product (PRODUCT_ID,DISPLAY_NAME,DESCRIPTION,LEVEL,PARENT_PRODUCT_ID,COST,CURRENCY_CODE,DISCOUNT_PERCENTAGE,STATUS)
values (9,'Logistics Integration','Logistics Integration',1,4,20,'USD',0,'A');
insert into product (PRODUCT_ID,DISPLAY_NAME,DESCRIPTION,LEVEL,PARENT_PRODUCT_ID,COST,CURRENCY_CODE,DISCOUNT_PERCENTAGE,STATUS)
values (10,'Import Operations','Import Operations',0,0,0,'USD',0,'A');
insert into product (PRODUCT_ID,DISPLAY_NAME,DESCRIPTION,LEVEL,PARENT_PRODUCT_ID,COST,CURRENCY_CODE,DISCOUNT_PERCENTAGE,STATUS)
values (11,'Import Shipment','Import Shipment',1,10,20,'USD',0,'A');
insert into product (PRODUCT_ID,DISPLAY_NAME,DESCRIPTION,LEVEL,PARENT_PRODUCT_ID,COST,CURRENCY_CODE,DISCOUNT_PERCENTAGE,STATUS)
values (12,'Customs Filing','Customs Filing',1,10,20,'USD',0,'A');
insert into product (PRODUCT_ID,DISPLAY_NAME,DESCRIPTION,LEVEL,PARENT_PRODUCT_ID,COST,CURRENCY_CODE,DISCOUNT_PERCENTAGE,STATUS)
values (13,'Landed Cost','Landed Cost',1,10,20,'USD',0,'A');
insert into product (PRODUCT_ID,DISPLAY_NAME,DESCRIPTION,LEVEL,PARENT_PRODUCT_ID,COST,CURRENCY_CODE,DISCOUNT_PERCENTAGE,STATUS)
values (14,'Publications','Publications',0,0,0,'USD',0,'A');
insert into product (PRODUCT_ID,DISPLAY_NAME,DESCRIPTION,LEVEL,PARENT_PRODUCT_ID,COST,CURRENCY_CODE,DISCOUNT_PERCENTAGE,STATUS)
values (15,'Unlimited Access','Unlimited Access',1,14,20,'USD',0,'A');
insert into product (PRODUCT_ID,DISPLAY_NAME,DESCRIPTION,LEVEL,PARENT_PRODUCT_ID,COST,CURRENCY_CODE,DISCOUNT_PERCENTAGE,STATUS)
values (16,'Annotate Online','Annotate Online',1,14,20,'USD',0,'A');
insert into product (PRODUCT_ID,DISPLAY_NAME,DESCRIPTION,LEVEL,PARENT_PRODUCT_ID,COST,CURRENCY_CODE,DISCOUNT_PERCENTAGE,STATUS)
values (17,'Consulting Services','Consulting Services',0,0,0,'USD',0,'A');
insert into product (PRODUCT_ID,DISPLAY_NAME,DESCRIPTION,LEVEL,PARENT_PRODUCT_ID,COST,CURRENCY_CODE,DISCOUNT_PERCENTAGE,STATUS)
values (18,'Basic','Basic',1,17,20,'USD',0,'A');
insert into product (PRODUCT_ID,DISPLAY_NAME,DESCRIPTION,LEVEL,PARENT_PRODUCT_ID,COST,CURRENCY_CODE,DISCOUNT_PERCENTAGE,STATUS)
values (19,'Annotate Online','Advanced',1,17,20,'USD',0,'A');


SET IDENTITY_INSERT product OFF
GO