CREATE TABLE `COUNTRY` (
  `COUNTRY_CODE` VARCHAR(4) NOT NULL,
  `COUNTRY_NAME` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`COUNTRY_CODE`)
) ;

CREATE TABLE `CURRENCY` (
  `CURRENCY_CODE` VARCHAR(4) NOT NULL,
  `DESCRIPTION` VARCHAR(50) DEFAULT NULL,
  `BASE_CURRENCY_CODE` VARCHAR(4) DEFAULT NULL,
  `UNIT_VALUE` DECIMAL(16,2) DEFAULT NULL,
  PRIMARY KEY (`CURRENCY_CODE`)
) ;

CREATE TABLE `PRODUCT` (
  `PRODUCT_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DISPLAY_NAME` VARCHAR(50) DEFAULT NULL,
  `DESCRIPTION` VARCHAR(500) DEFAULT NULL,
  `LEVEL` INT(11) DEFAULT NULL,
  `PARENT_PRODUCT_ID` INT(11) DEFAULT NULL,
  `COST` DECIMAL(16,2) DEFAULT NULL,
  `CURRENCY_CODE` VARCHAR(4) DEFAULT NULL,
  `DISCOUNT_PERCENTAGE` DECIMAL(3,2) DEFAULT NULL,
  `STATUS` VARCHAR(1) DEFAULT NULL,
  PRIMARY KEY (`PRODUCT_ID`)
) ;

CREATE TABLE `subscription_transaction` (
  `TRANSACTION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SUBSCRIPTION_ID` int(11) DEFAULT NULL,
  `AMOUNT` decimal(16,2) DEFAULT NULL,
  `USER_BILLING_ID` int(11) DEFAULT NULL,
  `TRANSACTION_STATUS` varchar(20) DEFAULT NULL,
  `CREATED_ON` datetime DEFAULT NULL,
  PRIMARY KEY (`TRANSACTION_ID`)
);

CREATE TABLE `SUBSCRIPTION` (
  `SUBSCRIPTION_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TOTAL_COST` DECIMAL(16,2) DEFAULT NULL,
  `CURRENCY_CODE` VARCHAR(4) DEFAULT NULL,
  `NO_OF_USERS` INT(11) DEFAULT NULL,
  `NO_OF_COUNTRIES` INT(11) DEFAULT NULL,
  `TOTAL_DISCOUNT` DECIMAL(16,2) DEFAULT NULL,
  `EFFECTIVE_FROM_DATE` DATETIME DEFAULT NULL,
  `EFFECTIVE_TO_DATE` DATETIME DEFAULT NULL,
  `CREATED_ON` DATETIME DEFAULT NULL,
  `MODIFIED_ON` DATETIME DEFAULT NULL,
  `STATUS` VARCHAR(1) DEFAULT NULL,
  PRIMARY KEY (`SUBSCRIPTION_ID`)
) ;

CREATE TABLE `SUBSCRIPTION_COUNTRY` (
  `SUBSCRIPTION_ID` INT(11) NOT NULL,
  `COUNTRY_CODE` VARCHAR(4) NOT NULL,
  `CREATED_ON` DATETIME DEFAULT NULL,
  `MODIFIED_ON` DATETIME DEFAULT NULL,
  `STATUS` VARCHAR(1) DEFAULT NULL,
  PRIMARY KEY (`SUBSCRIPTION_ID`,`COUNTRY_CODE`)
) ;

CREATE TABLE `SUBSCRIPTION_PRODUCT` (
  `SUBSCRIPTION_ID` INT(11) NOT NULL,
  `PRODUCT_ID` INT(11) NOT NULL,
  `CREATED_ON` DATETIME DEFAULT NULL,
  `MODIFIED_ON` DATETIME DEFAULT NULL,
  `STATUS` VARCHAR(1) DEFAULT NULL,
  PRIMARY KEY (`SUBSCRIPTION_ID`,`PRODUCT_ID`)
) ;

CREATE TABLE `SUBSCRIPTION_USER` (
  `SUBSCRIPTION_ID` INT(11) NOT NULL,
  `USER_ID` INT(11) NOT NULL,
  `CREATED_ON` DATETIME DEFAULT NULL,
  `MODIFIED_ON` DATETIME DEFAULT NULL,
  `STATUS` VARCHAR(1) DEFAULT NULL,
  PRIMARY KEY (`SUBSCRIPTION_ID`,`USER_ID`)
) ;

CREATE TABLE `USER` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(50) DEFAULT NULL,
  `FIRST_NAME` VARCHAR(50) DEFAULT NULL,
  `LAST_NAME` VARCHAR(50) DEFAULT NULL,
  `EMAIL_ID` VARCHAR(50) DEFAULT NULL,
  `PHONE` VARCHAR(20) DEFAULT NULL,
  `COMPANY_NAME` VARCHAR(50) DEFAULT NULL,
  `IMAGE` BLOB,
  `PASSWORD` VARCHAR(50) DEFAULT NULL,
  `RESET_PASSWORD_FLAG` VARCHAR(1) DEFAULT NULL,
  `USER_TYPE` VARCHAR(1) DEFAULT NULL,
  `PARENT_USER_ID` INT(11),
  `CREATED_ON` DATETIME DEFAULT NULL,
  `MODIFIED_ON` DATETIME DEFAULT NULL,
  `PWD_CHANGE_DATETIME` DATETIME DEFAULT NULL,
  `LAST_LOGGED_IN` DATETIME DEFAULT NULL,
  `STATUS` VARCHAR(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ;
alter table `user` add column sbu varchar(4);

CREATE TABLE `user_billing` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) DEFAULT NULL,
  `IS_PRIMARY` varchar(1) DEFAULT NULL,
  `CARD_NO` mediumtext,
  `EXP_DATE` datetime DEFAULT NULL,
  `FIRST_NAME` varchar(50) DEFAULT NULL,
  `LAST_NAME` varchar(50) DEFAULT NULL,
  `ADDRESS1` varchar(50) DEFAULT NULL,
  `ADDRESS2` varchar(50) DEFAULT NULL,
  `CITY` varchar(50) DEFAULT NULL,
  `STATE` varchar(50) DEFAULT NULL,
  `COUNTRY_CODE` varchar(4) DEFAULT NULL,
  `ZIPCODE` int(11) DEFAULT NULL,
  `CREATED_ON` datetime DEFAULT NULL,
  `MODIFIED_ON` datetime DEFAULT NULL,
  `STATUS` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `SUPPORT_CASE` (
  `TICKET_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` VARCHAR(2000),
  `CATEGORY` INT(10),
  `PRIORITY` VARCHAR(1) ,
  `CREATED_BY` INT(10),
  `CREATED_ON` DATETIME ,
  `ASSIGNED_TO` INT(10),
  `ASSIGNED_ON` DATETIME,
  `STATUS` VARCHAR(1),
  PRIMARY KEY (`TICKET_ID`)
) ;

CREATE TABLE `CASE_LOG` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `TICKET_ID` INT(10),
  `MESSAGE` VARCHAR(2000) DEFAULT NULL,
  `MESSAGE_BY` INT(10),
  `MESSAGE_ON` DATETIME DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ;

create table `ALERTS`(
ID INT(10) NOT NULL AUTO_INCREMENT,
DESCRIPTION VARCHAR(1000),
`EFFECTIVE_FROM_DATE` DATETIME ,
`EFFECTIVE_TO_DATE` DATETIME ,
`STATUS` VARCHAR(1),
PRIMARY KEY (`ID`)
);
alter table `ALERTS` add column USER_ID INT(10);

create table `MESSAGES`(
ID INT(10) NOT NULL AUTO_INCREMENT,
USER_ID INT(10),
DESCRIPTION VARCHAR(1000),
`CREATED_DATE` DATETIME ,
`STATUS` VARCHAR(1),
TICKET_ID INT(10),
PRIMARY KEY (`ID`)
);


CREATE TABLE SHIPMENTS(
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	SHIPMENT_NO VARCHAR(100),
	EXPORT_DATE DATETIME,
	EXPORT_COUNTRY_NAME VARCHAR(100),
	EXPORT_COUNTRY_CODE VARCHAR(10),
	ULT_CONSIGNEE_COUNTRY_NAME VARCHAR(100),
	ULT_CONSIGNEE_COUNTRY_CODE VARCHAR(10),	
	EXPORTER_FIRST_NAME VARCHAR(100),
	EXPORTER_LAST_NAME VARCHAR(100),
	EXPORTER_COMPANY_NAME VARCHAR(100),
	EXPORTER_PHONE_NO VARCHAR(30),
	EXPORTER_EMAIL VARCHAR(80),
	EXPORTER_NAME VARCHAR(100),
	EXPORTER_ADDR_LINE1 VARCHAR(200),
	EXPORTER_ADDR_LINE2 VARCHAR(200),
	EXPORTER_CITY VARCHAR(100),
	EXPORTER_STATE VARCHAR(100),
	EXPORTER_COUNTRY VARCHAR(10),
	EXPORTER_COUNTRY_NAME VARCHAR(100),
	EXPORTER_ZIP VARCHAR(50),
	USPPI_MOT VARCHAR(50),
	USPPI_FIRST_NAME VARCHAR(100),
	USPPI_LAST_NAME VARCHAR(100),
	USPPI_PHONE VARCHAR(30),
	USPPI_PORT_EXPORT VARCHAR(100),
	USPPI_EXPORTER_ID VARCHAR(100),
	USPPI_EXPORTER_IDTYPE VARCHAR(100),
	
	UTL_CONS_NAME VARCHAR(200),
	UTL_CONS_FIRST_NAME VARCHAR(200),
	UTL_CONS_LAST_NAME VARCHAR(200),
	UTL_CONS_ADDR1 VARCHAR(200),
	UTL_CONS_ADDR2 VARCHAR(200),
	UTL_CONS_CITY VARCHAR(200),
	UTL_CONS_STATE VARCHAR(200),
	UTL_CONS_COUNTRY_CODE VARCHAR(200),
	UTL_CONS_COUNTRY_NAME VARCHAR(200),
	UTL_CONS_ZIP VARCHAR(200),
	UTL_CONS_COMPANY_NAME VARCHAR(200),
	UTL_CONS_PHONE VARCHAR(200),
	UTL_CONS_EMAIL VARCHAR(200),
	
	INTER_CONS_NAME VARCHAR(200),
	INTER_CONS_FIRST_NAME VARCHAR(200),
	INTER_CONS_LAST_NAME VARCHAR(200),
	INTER_CONS_ADDR1 VARCHAR(200),
	INTER_CONS_ADDR2 VARCHAR(200),
	INTER_CONS_CITY VARCHAR(200),
	INTER_CONS_STATE VARCHAR(200),
	INTER_CONS_COUNTRY_CODE VARCHAR(200),
	INTER_CONS_COUNTRY_NAME VARCHAR(200),
	INTER_CONS_ZIP VARCHAR(200),
	INTER_CONS_COMPANY_NAME VARCHAR(200),
	INTER_CONS_PHONE VARCHAR(200),
	INTER_CONS_EMAIL VARCHAR(200),
	
	FREIGHT_FW_NAME VARCHAR(200),
	FREIGHT_FW_FIRST_NAME VARCHAR(200),
	FREIGHT_FW_LAST_NAME VARCHAR(200),
	FREIGHT_FW_ADDR1 VARCHAR(200),
	FREIGHT_FW_ADDR2 VARCHAR(200),
	FREIGHT_FW_CITY VARCHAR(200),
	FREIGHT_FW_STATE VARCHAR(200),
	FREIGHT_FW_COUNTRY_CODE VARCHAR(200),
	FREIGHT_FW_COUNTRY_NAME VARCHAR(200),
	FREIGHT_FW_ZIP VARCHAR(200),
	FREIGHT_FW_COMPANY_NAME VARCHAR(200),
	FREIGHT_FW_PHONE VARCHAR(200),
	FREIGHT_FW_EMAIL VARCHAR(200),
		
	PAYMENT_TERMS VARCHAR(200),
	INCO_TERMS VARCHAR(200),
	CURRENCY VARCHAR(50),
	CONVERSION_RATE DECIMAL(16,2),
	PO_NUMBER VARCHAR(200),
	MODE_OF_TRANSPORT VARCHAR(100),
	FREIGHT_CHARGES_PAID_BY VARCHAR(200),
	FOREIGN_VAT_PAID_BY VARCHAR(200),
	CUSTOM_DUTY_PAID_BY VARCHAR(200),
	CHARGE_DESC VARCHAR(200),
	CHARGE_AMT DECIMAL(16,4),
	DROP_SHIPMENT VARCHAR(1),
	SHIP_TO VARCHAR(50),
	BILL_TO VARCHAR(50),
	CONTAIN_PERSONAL_EFFECT VARCHAR(1),
	INSURANCE_REQUIRED VARCHAR(1),
	CHARGE_TO_CUSTOMER VARCHAR(1),
	PRINT_ON_DOC VARCHAR(1),
	
	SPECIAL_INSTRUCTION VARCHAR(255),
	SHIPMENT_INSTRUCTION VARCHAR(255),
	
	SCREENING_STATUS varchar(20),
	SCREENED_ON DATETIME,
	LS_STATUS varchar(10),
	
	STATUS varchar(20),
	CREATED_ON DATETIME,
	CREATED_BY VARCHAR(20),
	MODIFIED_ON DATETIME,
	MODIFIED_BY VARCHAR(20),
	PRIMARY KEY (`ID`)
);

alter table shipments add constraint shipNo_unique UNIQUE(shipment_no);
 
CREATE TABLE SHIPMENT_ITEM(
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	ITEM_NO INT NOT NULL,
	SHIPMENT_ID INT,
	PART_NO VARCHAR(255),
	USML_CATEGORY VARCHAR(255),
	HTS_SCHEDULE_B VARCHAR(50),
	HTS_SCHEDULE_UOM VARCHAR(50),
	ECCN VARCHAR(100),
	IMPORT_HTS VARCHAR(50),
	IMPORT_HTS_UOM VARCHAR(50),
	COO VARCHAR(50),
	MANUFACTURER VARCHAR(100),
	SERIAL_NUMBERS TEXT,
	PRODUCT_DESC TEXT,
	INVOICE_QTY DECIMAL(16,4),
	INVOICE_VALUE DECIMAL(16,4),
	DISCOUNT DECIMAL(16,2),
	CURRENCY VARCHAR(100),
	CONVERSION_RATE DECIMAL(16,4),
	WHOLESALE_RATE DECIMAL(16,4),
	UNIT_PRICE DECIMAL(16,4),
	WHOLESALE_VALUE DECIMAL(16,4),
	GROSS_WEIGHT DECIMAL(16,4),
	NET_WEIGHT DECIMAL(16,4),	
	
	LICENSE_REQUIRED VARCHAR(10),
	SCREEN_TYPE VARCHAR(20),
	SCREENED_ON DATETIME,
	
	FOREIGN KEY (SHIPMENT_ID) REFERENCES SHIPMENTS(id),
	PRIMARY KEY (`ID`)
);

CREATE TABLE SHIPMENT_CARTON(
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	SHIPMENT_ID INT,
	PACKAGE_NO INT,
	CARTON_NO INT,
	HAZMAT VARCHAR(100),
	DIMENSION_UOM VARCHAR(100),
	WEIGHT_UOM VARCHAR(100),
	LENGTH DECIMAL(16,4),
	WIDTH DECIMAL(16,4),
	HEIGHT DECIMAL(16,4),
	GROSS_WEIGHT DECIMAL(16,4),
	NET_WEIGHT DECIMAL(16,4),
	FOREIGN KEY (SHIPMENT_ID) REFERENCES SHIPMENTS(id),
	PRIMARY KEY (`ID`)
);

CREATE TABLE SHIPMENT_DOCS(
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	SHIPMENT_ID int not null,
	FILE_TYPE VARCHAR(100),
	FILE_NAME VARCHAR(255),
	FILE_PATH VARCHAR(255),
	CREATED_ON DATETIME,
	CREATED_BY VARCHAR(20),
	MODIFIED_ON DATETIME,
	MODIFIED_BY VARCHAR(20),
	FOREIGN KEY (SHIPMENT_ID) REFERENCES SHIPMENTS(id),
	PRIMARY KEY(ID)
);

CREATE TABLE STATE_PROVINCE (
	STATE_CODE varchar(10) NOT NULL,
	STATE_NAME nvarchar(100),
	COUNTRY_CODE varchar(4),
	STATUS varchar(1),
	CREATED_BY varchar(50),
	CREATED_ON datetime,
	MODIFIED_BY varchar(50),
	MODIFIED_ON datetime,
	PUBLISH_TIME datetime,
 	PRIMARY KEY (
		STATE_CODE,
		COUNTRY_CODE
	)
);

CREATE TABLE AIRPORT(
	DESTINATION_CODE varchar(3) NOT NULL,
	DESTINATION_NAME varchar(1000) NULL,
	STATUS varchar(1) NULL,
	MODIFIED_ON datetime NULL,
	PUBLISH_TIME datetime NULL,
	CREATED_BY varchar(20) NULL,
	CREATED_ON datetime NOT NULL,
	MODIFIED_BY varchar(20) NULL,
	PRIMARY KEY 
	(
		DESTINATION_CODE
	)
);

CREATE TABLE CARRIER(
	CARRIER_CODE varchar(6) NOT NULL,
	SCAC_IATA_CODE varchar(6) NULL,
	SCAC_IATA_FLAG varchar(1) NULL,
	DESCRIPTION varchar(150) NULL,
	SCREENING_STATUS varchar(1) NULL,
	STATUS varchar(1) NULL,
	MODIFIED_ON datetime NULL,
	PUBLISH_TIME datetime NULL,
	CREATED_BY varchar(20) NULL,
	CREATED_ON datetime NOT NULL,
	MODIFIED_BY varchar(20) NULL,
	PRIMARY KEY 
	(
		CARRIER_CODE
	)
);

CREATE TABLE CLIENT(
	ACCOUNT_ID varchar(20) NOT NULL,
	CLIENT_NAME varchar(100) NULL,
	STATUS varchar(20) NULL,
	EMAIL_ID varchar(100) NULL,
	PASSWORD varchar(100) NULL,
	CREATED_DATE datetime NULL,
	MODIFIED_DATE datetime NULL,
	CREATED_BY varchar(100) NULL,
	MODIFIED_BY varchar(20) NULL,
	SERVER_NAME varchar(250) NOT NULL,
	HOST_NAME varchar(250) NOT NULL,
	CLIENT_IP_ADD varchar(100) NULL,
	PRIMARY KEY  
	(
		ACCOUNT_ID,
		SERVER_NAME,
		HOST_NAME
	)
);

CREATE TABLE CONTROLLING_AGENCY(
	AGENCY_CODE varchar(10) NOT NULL,
	AGENCY_NAME varchar(250) NULL,
	COUNTRY varchar(2) NOT NULL,
	STATUS varchar(1) NULL,
	MODIFIED_ON datetime NULL,
	PUBLISH_TIME datetime NULL,
	CREATED_BY varchar(20) NULL,
	CREATED_ON datetime NOT NULL,
	MODIFIED_BY varchar(20) NULL,
	PRIMARY KEY 
	(
		AGENCY_CODE,
		COUNTRY
	)
);


CREATE TABLE HTS(
	HTS_NO varchar(20) NOT NULL,
	PRIMARY_UNIT varchar(50) NULL,
	SECONDARY_UNIT varchar(50) NULL,
	HTS_DESC varchar(2500) NULL,
	STATUS varchar(1) NULL,
	COUNTRY_CODE varchar(4) NOT NULL,
	VALUE_EDIT_CODE varchar(3) NULL,
	VALUE_BOUNDS_LOW numeric(10, 5) NULL,
	VALUE_BOUNDS_HIGH numeric(10, 5) NULL,
	ENTRY_DATE_REST_CODE1 varchar(1) NULL,
	REST_CODE1_BEGIN_DATE datetime NULL,
	REST_CODE1_END_DATE datetime NULL,
	ENTRY_DATE_REST_CODE2 varchar(1) NULL,
	REST_CODE2_BEGIN_DATE datetime NULL,
	REST_CODE2_END_DATE datetime NULL,
	EDIT_COO_CODE varchar(2) NULL,
	QTY_EDIT_CODE varchar(5) NULL,
	QTY_EDIT_LOWER numeric(10, 5) NULL,
	QTY_EDIT_UPPER numeric(10, 5) NULL,
	RETURN_HTS_NUMBER varchar(20) NULL,
	RETURN_DUTY_COMP_MOD varchar(1) NULL,
	HTS_FILING_DESC varchar(30) NULL,
	EFF_FROM_DATE datetime NULL,
	EFF_TO_DATE datetime NULL,
	NO_OF_REPORTING_UOM numeric(2, 0) NULL,
	UOM3 varchar(50) NULL,
	DUTY_COMP_CODE varchar(1) NULL,
	BASE_RATE_INDICATOR varchar(1) NULL,
	COL1_RATE_SPEC numeric(12, 8) NULL,
	COL1_RATE_ADVA numeric(12, 8) NULL,
	COL1_RATE_OTHER numeric(12, 8) NULL,
	COL2_RATE_SPEC numeric(12, 8) NULL,
	COL2_RATE_ADVA numeric(12, 8) NULL,
	COL2_RATE_OTHER numeric(12, 8) NULL,
	CVD_APPLIES varchar(1) NULL,
	ADDITIONAL_TARIFF_REQUIRED varchar(1) NULL,
	PERMIT_LICENSE_INDICATOR varchar(2) NULL,
	GSP_EXCLUDED_COUNTRY_CODE varchar(50) NULL,
	OGA varchar(55) NULL,
	ADD_APPLIES varchar(1) NULL,
	QUOTA_APPLIES varchar(1) NULL,
	TEXTILE_CATEGORY varchar(3) NULL,
	SPI varchar(75) NULL,
	MODIFIED_ON datetime NULL,
	PUBLISH_TIME datetime NULL,
	CREATED_BY varchar(20) NULL,
	CREATED_ON datetime NOT NULL,
	MODIFIED_BY varchar(20) NULL,
	MPF_EXEMPT varchar(1) NULL,
	FORMAL_ENTRY_REQ varchar(1) NULL,
	DUTY_REFERENCE varchar(100) NULL,
    PRIMARY KEY 
	(
		HTS_NO,
		COUNTRY_CODE
	)
);

CREATE TABLE LANGUAGE(
	CODE varchar(4) NOT NULL,
	NAME varchar(40) NOT NULL,
    PRIMARY KEY 
	(
		CODE
	)
);

CREATE TABLE LICENSE_TYPES(
	LICENSE_TYPE varchar(10) NOT NULL,
	LICENSE_CODE varchar(5) NULL,
	DESCRIPTION varchar(2000) NULL,
	AGENCY_CODE varchar(10) NULL,
	STATUS varchar(1) NULL,
	COUNTRY varchar(2) NOT NULL,
	MODIFIED_ON datetime NULL,
	PUBLISH_TIME datetime NULL,
	CREATED_BY varchar(20) NULL,
	CREATED_ON datetime NOT NULL,
	MODIFIED_BY varchar(20) NULL,
	VALIDITY_PERIOD numeric(3, 0) NULL,
	TEMPORARY_USE varchar(1) NULL,
	TEMPORARY_TYPE varchar(2) NULL,
	TECHNICAL_DATA varchar(1) NULL,
	ACTIVITY_TYPE varchar(10) NULL,
	PRIMARY KEY 
	(
		LICENSE_TYPE,
		COUNTRY
	)
);

CREATE TABLE MODE_OF_TRANSPORT(
	MOT_CODE varchar(5) NOT NULL,
	MOT_DES varchar(100) NOT NULL,
	MOT_ID varchar(5) NULL,
	STATUS varchar(1) NULL,
	COUNTRY varchar(2) NOT NULL,
	CREATED_BY varchar(20) NULL,
	CREATED_ON datetime NULL,
	MODIFIED_BY varchar(20) NULL,
	MODIFIED_ON datetime NULL,
	PUBLISH_TIME datetime NULL,
	Type_of_Transport varchar(10) NULL,
	PRIMARY KEY 
	(
		MOT_CODE ASC,
		COUNTRY ASC
	)
);

CREATE TABLE UNIT(
	UNIT_CODE varchar(50) NOT NULL,
	UNIT_DESC varchar(100) NULL,
	STATUS varchar(1) NULL,
	PUBLISH_TIME datetime NULL,
	MODIFIED_ON datetime NULL,
	CREATED_BY varchar(20) NULL,
	CREATED_ON datetime NULL,
	MODIFIED_BY varchar(20) NULL,
	COUNTRY_CODE varchar(2) NOT NULL,
	PRIMARY KEY 
	(
		UNIT_CODE,
		COUNTRY_CODE 
	)
);

CREATE TABLE UNIT_CONVERSION(
	UNIT1 varchar(50) NOT NULL,
	UNIT2 varchar(50) NOT NULL,
	UNIT_CONVERSION_FACTOR numeric(35, 5) NULL,
	STATUS varchar(1) NULL,
	MODIFIED_ON datetime NULL,
	PUBLISH_TIME datetime NULL,
	CREATED_BY varchar(20) NULL,
	CREATED_ON datetime NULL,
	MODIFIED_BY varchar(20) NULL,
	COUNTRY_CODE varchar(2) NOT NULL,
	PRIMARY KEY 
	(
		UNIT1,
		UNIT2,
		COUNTRY_CODE
	)
);

CREATE TABLE SBU(
	SBU_CODE varchar(30) NOT NULL,
	SBU_NAME varchar(30) NOT NULL,
	SBU_STATUS VARCHAR(5),
	SBU_TYPE VARCHAR(15),
	COUNTRY_NAME VARCHAR(100),
	COUNTRY_CODE VARCHAR(5),
	TIMEZONE VARCHAR(50),
	CREATED_BY VARCHAR(20),
	CREATED_ON datetime NULL,
	MODIFIED_BY varchar(20) NULL,
	MODIFIED_ON datetime NULL,
	PRIMARY KEY 
	(
		SBU_CODE,
		SBU_NAME
	)
);

CREATE TABLE partner_url_details(
       ID int NOT NULL,
       PARTNER_NAME varchar(45),
       API_NAME varchar(45),
       URL varchar(200),
       PRIMARY KEY 
       (
              ID 
       )
);

ALTER TABLE partner_url_details ADD ACC_NO VARCHAR(50) ;
ALTER TABLE partner_url_details ADD USERNAME VARCHAR(50) ;
ALTER TABLE partner_url_details ADD PASSWORD VARCHAR(50) ;

CREATE TABLE security_params(
       ID int NOT NULL,
       SBU_CODE varchar(45) ,
       ACCOUNT varchar(45) ,
       PARTNER_NAME varchar(45) NOT NULL,
       USERNAME varchar(30) ,
       PASSWORD varchar(45) ,
       ACCOUNT_NUMBER varchar(45) ,
       METER_NUMBER varchar(45) ,
       LICENSE_NUMBER varchar(45) ,
       PRIMARY KEY 
       (
              ID 
       )
);
ALTER TABLE security_params ADD THIRD_PARTY_ACC_NO VARCHAR(45) ;
ALTER TABLE security_params ADD BILL_TO VARCHAR(20) ;
ALTER TABLE security_params ADD SPR_NAME VARCHAR(200) ;
ALTER TABLE security_params ADD SPR_CONTACT_FIRST_NAME VARCHAR(200) ;
ALTER TABLE security_params ADD SPR_CONTACT_MIDDLE_NAME VARCHAR(200) ;
ALTER TABLE security_params ADD SPR_CONTACT_LAST_NAME VARCHAR(200) ;
ALTER TABLE security_params ADD SPR_ADDR_LINE1 VARCHAR(255) ;
ALTER TABLE security_params ADD SPR_ADDR_LINE2 VARCHAR(255) ;
ALTER TABLE security_params ADD SPR_CITY_NAME VARCHAR(100) ;
ALTER TABLE security_params ADD SPR_CITY_CODE VARCHAR(10) ;
ALTER TABLE security_params ADD SPR_STATE_NAME VARCHAR(100) ;
ALTER TABLE security_params ADD SPR_STATE_CODE VARCHAR(10) ;
ALTER TABLE security_params ADD SPR_COUNTRY_NAME VARCHAR(100) ;
ALTER TABLE security_params ADD SPR_COUNTRY_CODE VARCHAR(10) ;
ALTER TABLE security_params ADD SPR_ZIP VARCHAR(50) ;
ALTER TABLE security_params ADD SPR_PHONENO VARCHAR(50) ;
ALTER TABLE security_params ADD SPR_EMAIL VARCHAR(100) ;
ALTER TABLE security_params ADD BILL_TO_NAME VARCHAR(200) ;
ALTER TABLE security_params ADD BILL_TO_FIRST_NAME VARCHAR(200) ;
ALTER TABLE security_params ADD BILL_TO_MIDDLE_NAME VARCHAR(200) ;
ALTER TABLE security_params ADD BILL_TO_LAST_NAME VARCHAR(200) ;
ALTER TABLE security_params ADD BILL_TO_ADDR_LINE1 VARCHAR(255) ;
ALTER TABLE security_params ADD BILL_TO_ADDR_LINE2 VARCHAR(255) ;
ALTER TABLE security_params ADD BILL_TO_CITY_NAME VARCHAR(100) ;
ALTER TABLE security_params ADD BILL_TO_CITY_CODE VARCHAR(10) ;
ALTER TABLE security_params ADD BILL_TO_STATE_NAME VARCHAR(100) ;
ALTER TABLE security_params ADD BILL_TO_STATE_CODE VARCHAR(10) ;
ALTER TABLE security_params ADD BILL_TO_COUNTRY_NAME VARCHAR(100) ;
ALTER TABLE security_params ADD BILL_TO_COUNTRY_CODE VARCHAR(10) ;
ALTER TABLE security_params ADD BILL_TO_ZIP VARCHAR(50) ;
ALTER TABLE security_params ADD BILL_TO_PHONENO VARCHAR(50) ;
ALTER TABLE security_params ADD BILL_TO_EMAIL VARCHAR(100) ;

create table SBU_CONFIG(
	   ID int NOT NULL AUTO_INCREMENT,
       SBU varchar(45),
       NAME varchar(255),
       CONFIG_VALUE varchar(255),
       DESCRIPTION MEDIUMTEXT,
       STATUS VARCHAR(20),       
       CREATED_ON datetime,
       CREATED_BY VARCHAR(50),
       MODIFIED_ON datetime,
       MODIFIED_BY VARCHAR(50),
       PRIMARY KEY 
       (
              ID 
       )
);

ALTER TABLE SHIPMENTS ADD EXPORTER_CODE VARCHAR(100);
ALTER TABLE SHIPMENTS ADD ULT_CONSIGNEE_CODE VARCHAR(100);
ALTER TABLE SHIPMENTS ADD INTER_CONSIGNEE_CODE VARCHAR(100);
ALTER TABLE SHIPMENTS ADD FF_CODE VARCHAR(100);

ALTER TABLE SHIPMENTS ADD SHIP_TO_CODE VARCHAR(100);
ALTER TABLE SHIPMENTS ADD SHIP_TO_NAME VARCHAR(200);
ALTER TABLE SHIPMENTS ADD SHIP_TO_CITY VARCHAR(50);
ALTER TABLE SHIPMENTS ADD SHIP_TO_STATE VARCHAR(50);
ALTER TABLE SHIPMENTS ADD SHIP_TO_COUNTRY VARCHAR(50);
ALTER TABLE SHIPMENTS ADD SHIP_TO_ZIP VARCHAR(30);
ALTER TABLE SHIPMENTS ADD SHIP_TO_ADDR1 VARCHAR(255);
ALTER TABLE SHIPMENTS ADD SHIP_TO_ADDR2 VARCHAR(255);

ALTER TABLE SHIPMENTS ADD BILL_TO_CODE VARCHAR(100);
ALTER TABLE SHIPMENTS ADD BILL_TO_NAME VARCHAR(200);
ALTER TABLE SHIPMENTS ADD BILL_TO_CITY VARCHAR(50);
ALTER TABLE SHIPMENTS ADD BILL_TO_STATE VARCHAR(50);
ALTER TABLE SHIPMENTS ADD BILL_TO_COUNTRY VARCHAR(50);
ALTER TABLE SHIPMENTS ADD BILL_TO_ZIP VARCHAR(30);
ALTER TABLE SHIPMENTS ADD BILL_TO_ADDR1 VARCHAR(255);
ALTER TABLE SHIPMENTS ADD BILL_TO_ADDR2 VARCHAR(255);
ALTER TABLE SHIPMENTS ADD AES_OPTION VARCHAR(20);

ALTER TABLE SHIPMENTS ADD FIILER_TYPE_ID VARCHAR(5);
ALTER TABLE SHIPMENTS ADD ULT_CONS_TYPE VARCHAR(50);
